homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.0916
  longitude: 5.1228
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

config:
hassio:

mqtt:
  broker: 10.10.10.20

mqtt_statestream:
  base_topic: satellite

hdmi_cec:
#  platform: media_player
  devices:
    Entone: 1.0.0.0
    Apple TV: 2.0.0.0
    Pi: 3.0.0.0

device_tracker:
  - platform: bluetooth_tracker
