homeassistant:
  name: Satellite
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam

# Enable for frontend 
#frontend:
#config:

mqtt:
  broker: 10.10.10.11

mqtt_statestream:
  base_topic: satellite

mqtt_eventstream:
  publish_topic: satellite/events

sensor:
  - platform: miflora
    mac: 'C4:7C:8D:66:42:FC'

device_tracker:
  - platform: bluetooth_tracker
#  - platform: bluetooth_le_tracker


